# Railway Configuration File
# This file configures your Railway deployment

[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
NODE_ENV = "production"
PORT = "3000"

# These will be set via Railway dashboard or GitHub secrets
# DATABASE_URL = "postgresql://..."
# JWT_SECRET = "..."
# OPENAI_API_KEY = "..."
